on:
  schedule:
    - cron: 0 0 * * * # Jalankan setiap 24 jam

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Instal Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Jalankan skrip
        run: node index.js
          node index.js
          sleep 86400 # Tidur selama 24 jam
